/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: GPIO Example for 
*              ModusToolbox. This example demonstrates how to configure the GPIO
*              registers using the GPDMA peripheral.
*
* Related Document: See README.md
*
*******************************************************************************
*
* Copyright (c) 2021, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "xmc_dma.h"

/*******************************************************************************
* Macros
*******************************************************************************/

/* DMA Channel 0 */
#define GPDMA_CHANNEL_NUM 0

#ifdef CYBSP_USER_LED2_PIN
/* Data Length of the GPIO buffer */
#define DATA_SIZE 8UL

#else
/* Data Length of the GPIO buffer */
#define DATA_SIZE 2UL
#endif

/*******************************************************************************
* Variables
*******************************************************************************/

#ifdef CYBSP_USER_LED2_PIN
/* GPIO logic levels to be sent to the OMR register. This data format ensures 
 * 50% duty cycle for CYBSP_USER_LED and 25% duty cycle for CYBSP_USER_LED2
 */
uint32_t gpio_data[DATA_SIZE] = {
    (XMC_GPIO_OUTPUT_LEVEL_HIGH << CYBSP_USER_LED_PIN),     /* Logic HIGH to USER_LED */
    (XMC_GPIO_OUTPUT_LEVEL_HIGH << CYBSP_USER_LED2_PIN),    /* Logic HIGH to USER_LED2 */
    (XMC_GPIO_OUTPUT_LEVEL_LOW  << CYBSP_USER_LED_PIN),     /* Logic LOW to USER_LED */
    (XMC_GPIO_OUTPUT_LEVEL_LOW  << CYBSP_USER_LED2_PIN),    /* Logic LOW to USER_LED2 */
    (XMC_GPIO_OUTPUT_LEVEL_HIGH << CYBSP_USER_LED_PIN),     /* Logic HIGH to USER_LED */
    (XMC_GPIO_OUTPUT_LEVEL_LOW  << CYBSP_USER_LED2_PIN),    /* Logic LOW to USER_LED2 */
    (XMC_GPIO_OUTPUT_LEVEL_LOW  << CYBSP_USER_LED_PIN),     /* Logic LOW to USER_LED */
    (XMC_GPIO_OUTPUT_LEVEL_LOW  << CYBSP_USER_LED2_PIN),    /* Logic LOW to USER_LED2 */
};

#else
/* GPIO logic levels to be sent to the OMR register. This data format ensures
 * 50% duty cycle for CYBSP_USER_LED.
 */
uint32_t gpio_data[DATA_SIZE] = {
    (XMC_GPIO_OUTPUT_LEVEL_HIGH << CYBSP_USER_LED_PIN),   /* Logic HIGH to USER_LED */
    (XMC_GPIO_OUTPUT_LEVEL_LOW << CYBSP_USER_LED_PIN),    /* Logic HIGH to USER_LED2 */
};
#endif

/* DMA channel configuration. Since USER_LED and USER_LED2 are in the same 
 * port, destination address is same for both the LEDs.
 */
const XMC_DMA_CH_CONFIG_t dma_ch_config =
{
    {
        .enable_interrupt = false,                                         /* Interrupts enabled ? */
        .dst_transfer_width = XMC_DMA_CH_TRANSFER_WIDTH_32,                /* Destination transfer width */
        .src_transfer_width = XMC_DMA_CH_TRANSFER_WIDTH_32,                /* Source transfer width */
        .dst_address_count_mode = XMC_DMA_CH_ADDRESS_COUNT_MODE_NO_CHANGE, /* Destination address count mode */
        .src_address_count_mode = XMC_DMA_CH_ADDRESS_COUNT_MODE_INCREMENT, /* Source address count mode */
        .dst_burst_length = XMC_DMA_CH_BURST_LENGTH_1,                     /* Destination burst length */
        .src_burst_length = XMC_DMA_CH_BURST_LENGTH_1,                     /* Source burst length */
        .enable_src_gather = false,                                        /* Source gather enabled? */
        .enable_dst_scatter = false,                                       /* Destination scatter enabled? */
        .transfer_flow = XMC_DMA_CH_TRANSFER_FLOW_M2M_DMA,                 /* Transfer flow */
    },
    .src_addr = (uint32_t)&gpio_data[0],                                               /* Source address */
    .dst_addr = (uint32_t) & (CYBSP_USER_LED_PORT->OMR),                               /* Destination address */
    .block_size = DATA_SIZE,                                                           /* Block size */
    .transfer_type = XMC_DMA_CH_TRANSFER_TYPE_MULTI_BLOCK_SRCADR_RELOAD_DSTADR_RELOAD, /* Transfer type */
    .priority = XMC_DMA_CH_PRIORITY_0,                                                 /* Priority level */
    .src_handshaking = XMC_DMA_CH_SRC_HANDSHAKING_SOFTWARE,                            /* Source handshaking */
    .dst_handshaking = XMC_DMA_CH_DST_HANDSHAKING_SOFTWARE                             /* Destination handshaking */
};

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. This function performs the initial setup of the 
* device and initializes the GPDMA peripheral. The GPIO logic levels are 
* transferred from the SRAM to the GPIO OMR register.
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize and enable the GPDMA peripheral */
    XMC_DMA_Init(XMC_DMA0);

    /* Initialize the DMA channel 0 with provided channel configuration */
    XMC_DMA_CH_Init(XMC_DMA0, GPDMA_CHANNEL_NUM, &dma_ch_config);

    /* Enable the DMA channel to initiate transfer */
    XMC_DMA_CH_Enable(XMC_DMA0, GPDMA_CHANNEL_NUM);

    while (1);
}

/* [] END OF FILE */
